Hm33
floriangeyer21/movie-store pull request #5
Opened 2020-10-12 12:03 UTC by floriangeyer21

2020-10-12 18:33 UTC, DariiaPikul reviewed
I guess you used to have an abstract DAO class since there are so many DAO implementations classes in this PR
Did you really need to remove it?
Also, left some minor comments

2020-10-12 18:33 UTC, DariiaPikul commented on src/main/java/com/movie/store/service/impl/ShoppingCartServiceImpl.java
> +        shoppingCartDao.update(shoppingCart);
Doesn't this method have return value type ShoppingCart?

2020-10-12 18:33 UTC, DariiaPikul commented on src/main/java/com/movie/store/service/impl/ShoppingCartServiceImpl.java
> +        //  Case with deleting tickets from orders_tickets and shopping_-crts_tickets
Do you need these comments?

2020-10-12 18:33 UTC, DariiaPikul commented on src/main/java/com/movie/store/dao/impl/ShoppingCartDaoImpl.java
> +                            + "join fetch s.user "
Why fetching user since you've got the `@ManyToOne` connection here?

2020-10-12 20:15 UTC, KseniiaMakarova requested changes
try making a commit into this branch to refresh the state of this branch comparing to `master`
currently I can see classes from the previous HW here

please pay attention to the mistakes I addressed in our conversation

2020-10-12 20:15 UTC, KseniiaMakarova commented on src/main/resources/hibernate.cfg.xml
> +<!--        <property name="hibernate.generate_statistics">true</property>-->
let's remove or uncomment this

2020-10-12 21:17 UTC, KseniiaMakarova requested changes

2020-10-12 21:17 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/Main.java
> +        cinemaHall.setMovieSessions(List.of(movieSession, movieSession1));
there should be one-way relationship here
see the UML of this project

2020-10-12 21:17 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/Main.java
> +        movieSessionService.add(movieSession1);
in our conversation I have noticed that `movieSessionService.findAvailableSessions()` should be refactored
please do it

2020-10-12 21:17 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/Main.java
>          ShoppingCart shoppingCart = shoppingCartService.getByUser(user);
let's swap these two lines and use local variable for logging

2020-10-12 21:17 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/model/Order.java
> +@EqualsAndHashCode
is `@EqualsAndHashCode` part of `@Data`?

2020-10-12 21:17 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/model/ShoppingCart.java
> +@EqualsAndHashCode
here as well

2020-10-12 21:17 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/model/ShoppingCart.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
we don't need this - we have `@MapsId`

2020-10-12 21:17 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/model/Ticket.java
> +@EqualsAndHashCode
is `@EqualsAndHashCode` part of `@Data`?

2020-10-12 21:17 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/model/ShoppingCart.java
> +    private Set<Ticket> tickets = new HashSet<>();
does it work without replacing `List` with `Set`?

2020-10-12 21:18 UTC, KseniiaMakarova reviewed
let's also remove `log4j.logger.org.hibernate.SQL=DEBUG` property

2020-10-13 10:25 UTC, KseniiaMakarova approved these changes

2020-10-13 10:57 UTC, merged