add CinemaHallController, OrderController, ShoppingCartController
floriangeyer21/movie-store pull request #9
Opened 2020-10-26 16:27 UTC by floriangeyer21

2020-10-26 23:07 UTC, DmGrt reviewed
Good job!

2020-10-26 23:07 UTC, DmGrt commented on src/main/java/com/movie/store/dao/impl/MovieSessionDaoImpl.java
> +            return query.uniqueResult();
You can use session.get() here)

2020-10-26 23:07 UTC, DmGrt commented on src/main/java/com/movie/store/dao/impl/UserDaoImpl.java
> +            User user = query.uniqueResult();
Same

2020-10-27 08:41 UTC, KseniiaMakarova requested changes

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/controllers/CinemaHallController.java
> +    private CinemaHallMapper cinemaHallMapper;
```suggestion
    private final CinemaHallService cinemaHallService;
    private final CinemaHallMapper cinemaHallMapper;
```

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/controllers/CinemaHallController.java
> +    public void addCinemaHalls(@RequestBody CinemaHallRequestDto cinemaHallRequestDto) {
```suggestion
    public void addCinemaHall(@RequestBody CinemaHallRequestDto cinemaHallRequestDto) {
```

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/controllers/CinemaHallController.java
> +    public List<CinemaHallResponseDto> getAllCinemaHall() {
```suggestion
    public List<CinemaHallResponseDto> getAllCinemaHalls() {
```

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/controllers/CinemaHallController.java
> +                cinemaHallService.getAll());
what if you will need to map only one cinema hall? let's make the method in mapper take only one object

and call the method for each cinema hall

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/controllers/OrderController.java
> +    @PostMapping
add request mapping

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/controllers/OrderController.java
> +        return orderMapper.mapAllOrderToResponseDto(
same: make the method in mapper take only one object

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/controllers/ShoppingCartController.java
> +    public void addMovieSessions(@RequestParam("userId") Long userId,
```suggestion
    public void addMovieSession(@RequestParam Long userId,
```

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/controllers/ShoppingCartController.java
> +                                 @RequestBody Long movieSessionId) {
```suggestion
                                 @RequestParam Long movieSessionId) {
```

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/model/dto/CinemaHallRequestDto.java
> +    private int capacity;
what about description?

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/model/dto/CinemaHallResponseDto.java
> +    private int capacity;
same

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/model/dto/ShoppingCartResponseDto.java
> +    private Long userId;
aren't these the same?

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/service/impl/MovieSessionServiceImpl.java
> +    }
what is it for?

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/service/mappers/CinemaHallMapper.java
> +    public List<CinemaHallResponseDto> mapAllCinemaHallToResponseDto(List<CinemaHall> cinemaHalls) {
let's remove this method

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/service/mappers/OrderMapper.java
> +    public List<OrderResponseDto> mapAllOrderToResponseDto(List<Order> orders) {
same

2020-10-27 08:41 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/service/mappers/TicketMapper.java
> +    public Set<TicketResponseDto> mapAllTicketToResponseDto(Set<Ticket> tickets) {
same

2020-10-28 07:24 UTC, KseniiaMakarova requested changes

2020-10-28 07:24 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/controllers/CinemaHallController.java
> +    public List<CinemaHallResponseDto> getAllCinemaHall() {
```suggestion
    public List<CinemaHallResponseDto> getAllCinemaHalls() {
```

2020-10-28 07:24 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/controllers/ShoppingCartController.java
> +    public ShoppingCartController(ShoppingCartService shoppingCartService,
sometimes you use @Autowired before the constructor, sometimes not - let's be consistent

2020-10-28 07:24 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/controllers/UserController.java
> +    public UserResponseDto getUserByEmail(@RequestParam("email") String email) {
```suggestion
    public UserResponseDto getUserByEmail(@RequestParam String email) {
```

2020-10-28 07:24 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/dao/impl/UserDaoImpl.java
> +            return Optional.of(session.get(User.class, id));
what happens when we call `Optional.of(null)`?

2020-10-28 07:24 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/model/dto/TicketResponseDto.java
> +    private int capacity;
```suggestion
    private int cinemaHallCapacity;
```

2020-10-28 07:24 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/controllers/UserController.java
> +    private final UserMapper userMapper;
UserMapper class is not pushed to the PR

2020-10-28 07:24 UTC, KseniiaMakarova commented on src/main/java/com/movie/store/service/mappers/ShoppingCartMapper.java
> +    public ShoppingCartMapper(TicketMapper ticketMapper) {
```suggestion
    @Autowired
    public ShoppingCartMapper(TicketMapper ticketMapper) {
```

2020-10-28 09:44 UTC, floriangeyer21 commented on src/main/java/com/movie/store/controllers/CinemaHallController.java
> +                cinemaHallService.getAll());
Не совсем здесь понял. Нам же по заданию нужно вывести все cinema hall, а логику с выводом одного или нескольких я реализую в CinemaHallMapper. Богдан на лекции сегодня говорил что в контроллере не должно выбть бизнес логики.

2020-10-28 09:44 UTC, floriangeyer21 commented on src/main/java/com/movie/store/controllers/ShoppingCartController.java
> +                                 @RequestBody Long movieSessionId) {
У нас в задании ведь написано что это Post метод и в url только userId

2020-10-28 09:44 UTC, floriangeyer21 commented on src/main/java/com/movie/store/service/mappers/CinemaHallMapper.java
> +    public List<CinemaHallResponseDto> mapAllCinemaHallToResponseDto(List<CinemaHall> cinemaHalls) {
Здесь то же что выше писал. Мне кажется лучше в мапере иметь такой метод, чем в контроллере логику по маппингу одного листа в другой.

2020-10-28 09:44 UTC, floriangeyer21 commented on src/main/java/com/movie/store/controllers/UserController.java
> +    private final UserMapper userMapper;
Он просто у меня уже был с прошлого дз.

2020-10-28 09:53 UTC, floriangeyer21 commented on src/main/java/com/movie/store/model/dto/UserResponseDto.java
> -    private String password;
Насчет UserRequestDto, я использую его в AuthenticationController.

2020-10-28 10:03 UTC, KseniiaMakarova approved these changes

2020-10-28 15:59 UTC, merged